/**
 * Stable, locale-independent error codes returned by API routes in the
 * `error_code` field of the `{ success: false, error_code, message }` shape.
 *
 * Each code maps to a human-readable string under the `errors` namespace in
 * messages/{he,en}.json — resolve it on the client via messageForError() in
 * lib/api-error.ts. Codes are append-only and must never change once shipped.
 */
export type ErrorCode =
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "SERVER_ERROR"
  | "INVALID_REQUEST"
  | "VALIDATION_ERROR"
  | "NO_FIELDS_TO_UPDATE"
  | "RATE_LIMIT"
  | "EMAIL_SEND_FAILED"
  | "CLIENT_NOT_FOUND"
  | "CLIENT_REQUIRED"
  | "PROJECT_NOT_FOUND"
  | "TASK_NOT_FOUND"
  | "ENTRY_NOT_FOUND"
  | "RATE_NOT_FOUND"
  | "PROFILE_NOT_FOUND"
  | "USER_NOT_FOUND"
  | "FIXED_MONTHLY_FEE_REQUIRED"
  | "FIXED_MONTHLY_DATE_RANGE_INVALID"
  | "TIMER_NOT_FOUND"
  | "TIMER_ALREADY_PAUSED"
  | "TIMER_NOT_PAUSED"
  | "ENTRY_STATE_CHANGED"
  | "ENTRY_UNAVAILABLE"
  | "DOCUMENT_NOT_FOUND"
  | "DOCUMENT_LOCKED"
  | "LINE_NOT_FOUND"
  | "DELETE_REQUIRES_CANCELED"
  | "CANCEL_REQUIRES_PENDING"
  | "PAY_REQUIRES_PENDING"
  | "UNPAY_REQUIRES_PAID"
  | "REPORT_GENERATION_ERROR"
  | "REPORTS_INIT_LOAD_ERROR"
  | "EXCEL_GENERATION_ERROR"
  | "PRESETS_LOAD_ERROR"
  | "PRESET_SAVE_ERROR"
  | "PRESET_NOT_FOUND"
  | "PRESET_DELETE_ERROR"
  | "CURRENCY_RATES_LOAD_ERROR"
  | "CURRENCY_SAME_SOURCE_TARGET"
  | "CURRENCY_RATES_TABLE_MISSING"
  | "CURRENCY_RATE_SAVE_ERROR"
  | "CURRENCY_RATE_NOT_FOUND"
  | "CURRENCY_RATE_DELETE_ERROR"
  | "NO_FILE"
  | "INVALID_FILE_TYPE"
  | "FILE_TOO_LARGE"
  | "NO_FILE_TO_DELETE"
  | "SELF_ACTION_FORBIDDEN"
  | "PASSWORD_RESET_UNSUPPORTED"
  | "PLAN_LIMIT_REACHED"
  | "CLIENT_PLAN_LOCKED"
  | "UNKNOWN_ACTION";

/** Every known error code, for runtime checks / exhaustiveness. */
export const ERROR_CODES: readonly ErrorCode[] = [
  "UNAUTHORIZED",
  "FORBIDDEN",
  "SERVER_ERROR",
  "INVALID_REQUEST",
  "VALIDATION_ERROR",
  "NO_FIELDS_TO_UPDATE",
  "RATE_LIMIT",
  "EMAIL_SEND_FAILED",
  "CLIENT_NOT_FOUND",
  "CLIENT_REQUIRED",
  "PROJECT_NOT_FOUND",
  "TASK_NOT_FOUND",
  "ENTRY_NOT_FOUND",
  "RATE_NOT_FOUND",
  "PROFILE_NOT_FOUND",
  "USER_NOT_FOUND",
  "FIXED_MONTHLY_FEE_REQUIRED",
  "FIXED_MONTHLY_DATE_RANGE_INVALID",
  "TIMER_NOT_FOUND",
  "TIMER_ALREADY_PAUSED",
  "TIMER_NOT_PAUSED",
  "ENTRY_STATE_CHANGED",
  "ENTRY_UNAVAILABLE",
  "DOCUMENT_NOT_FOUND",
  "DOCUMENT_LOCKED",
  "LINE_NOT_FOUND",
  "DELETE_REQUIRES_CANCELED",
  "CANCEL_REQUIRES_PENDING",
  "PAY_REQUIRES_PENDING",
  "UNPAY_REQUIRES_PAID",
  "REPORT_GENERATION_ERROR",
  "REPORTS_INIT_LOAD_ERROR",
  "EXCEL_GENERATION_ERROR",
  "PRESETS_LOAD_ERROR",
  "PRESET_SAVE_ERROR",
  "PRESET_NOT_FOUND",
  "PRESET_DELETE_ERROR",
  "CURRENCY_RATES_LOAD_ERROR",
  "CURRENCY_SAME_SOURCE_TARGET",
  "CURRENCY_RATES_TABLE_MISSING",
  "CURRENCY_RATE_SAVE_ERROR",
  "CURRENCY_RATE_NOT_FOUND",
  "CURRENCY_RATE_DELETE_ERROR",
  "NO_FILE",
  "INVALID_FILE_TYPE",
  "FILE_TOO_LARGE",
  "NO_FILE_TO_DELETE",
  "SELF_ACTION_FORBIDDEN",
  "PASSWORD_RESET_UNSUPPORTED",
  "PLAN_LIMIT_REACHED",
  "CLIENT_PLAN_LOCKED",
  "UNKNOWN_ACTION",
] as const;
